image:
  repository: pavlom88/simple-docker-app
  tag: v1-1751459838
  pullPolicy: Always

serviceAccount:
  create: false
  name: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

ingress:
  enabled: false

autoscaling:
  enabled: false
